name: widgets_form
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  intl: ^0.15.7
  camera: ^0.5.3+1
  image_crop: ^0.3.1
  photo_view: ^0.2.2
  image: ^2.1.4
  path_provider: ^0.5.0
  flutter_custom_tabs: ^0.6.0
  webview_flutter: ^0.3.14+1
  flutter_inappbrowser: ^1.2.1
  dio: ^2.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true